services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - CORS_ORIGINS=http://localhost:4173,http://127.0.0.1:4173,http://localhost:5173,http://127.0.0.1:5173
      - PUBLIC_IMAGE_BASE_URL=http://localhost:3001
    ports:
      - "3001:3001"
    volumes:
      - server-data:/app/data
      - server-uploads:/app/uploads
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
    ports:
      - "4173:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  server-data:
  server-uploads:
